### ISSUE TITLE
Cannot read properties of undefined when using more than one middleware

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-dev-server#4]
```
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] Cannot read properties of undefined (reading 'url') (via TypeError)
[11ty] 
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'url')
[11ty]     at /Users/zachleat/Code/11ty-website/node_modules/@11ty/eleventy/src/Plugins/ServerlessBundlerPlugin.js:235:29
[11ty]     at /Users/zachleat/Code/11ty-website/node_modules/@11ty/eleventy/src/Plugins/ServerlessBundlerPlugin.js:250:16
[11ty]     at runMicrotasks (<anonymous>)
[11ty]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[11ty]     at async EleventyServeAdapter.onRequestHandler (/Users/zachleat/Code/11ty-website/node_modules/@11ty/eleventy-dev-server/server.js:305:9)
```

Ran into this when using more than one `EleventyServerlessBundlerPlugin` (which added more than one middleware)

**Comment by zachleat** [comment]
This will ship with 1.0.0-canary.2
