### ISSUE TITLE
Morphdom  throw errors on page update when using petite-vue

### ISSUE THREAD

**Issue by stormitornado** [11ty/eleventy-dev-server#71]
Hi!
Maybe it'll duplicate some issues, but I think this one can be solved.
I use Petite-Vue framework on my pages, and it provides some non-standart attributes like `@vue:mounted` and `@vue:unmounted`.
On page update I get this error in console:
```
[11ty][18:11:13.032 UTC] Morphdom error DOMException: Failed to execute 'setAttribute' on 'Element': '@vue:mounted' is not a valid attribute name.
    at morphAttrs (http://localhost:8080/.11ty/morphdom.js:37:26)
    at morphEl (http://localhost:8080/.11ty/morphdom.js:499:9)
    at morphChildren (http://localhost:8080/.11ty/morphdom.js:608:17)
    at morphEl (http://localhost:8080/.11ty/morphdom.js:509:9)
    at morphChildren (http://localhost:8080/.11ty/morphdom.js:608:17)
    at morphEl (http://localhost:8080/.11ty/morphdom.js:509:9)
    at morphChildren (http://localhost:8080/.11ty/morphdom.js:608:17)
    at morphEl (http://localhost:8080/.11ty/morphdom.js:509:9)
    at morphdom (http://localhost:8080/.11ty/morphdom.js:725:7)
    at EleventyReload.onreload (http://localhost:8080/.11ty/reload-client.js:200:17)
```
Is it possible to fix attribute parsing, and not just switch off diff-updates ?

**Comment by zachleat** [comment]
Can you supply the exact HTML that is causing the error? I couldn’t reproduce with a quick `@vue:mounted` attribute test.
