### ISSUE TITLE
Cannot locate Morphdom module in NPM Workspaces

### ISSUE THREAD

**Issue by ala-n** [11ty/eleventy-dev-server#77]
### Steps to Reproduce

The following project structure (with NPM workspaces):

- 📁 **root**
    - 📁 **11ty-package**
        - 📁 **view**
            - 📄 **index.html** // Some stuff to render, serve, and watch
        - 📄 **.eleventy.js** // 11ty config, so 11ty runs here
        - 📄 **package.json** // The one referencing @11ty/eleventy and @11ty/eleventy-dev-server
    - 📁 **another-package**
        - ...
    - 📁 **node_modules** // Everything, including `@11ty/eleventy-dev-server`, `@11ty/eleventy`, and `morphdom`, loads here (by the NPM workspaces feature to share dependencies between packages)
    - 📄 **package.json** // Root workspaces package 
    - 📄 **package-lock.json**

The server runs in the context of the `root/11ty-package` subpackage. 

The `domDiff` is enabled (default).

Any HTML-related changes lead to an exception during the watch process, with the following error:

```shell
[11ty] Unhandled rejection in promise: (more in DEBUG output)
[11ty] The "path" argument must be of type string or an instance of Buffer or URL. Received undefined (via TypeError)
[11ty]
[11ty] Original error stack trace: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
[11ty]     at Object.readFileSync (node:fs:451:42)
[11ty]     at EleventyDevServer._getFileContents (L:\DMT\smart-wc-library\node_modules\@11ty\eleventy\node_modules\@11ty\eleventy-dev-server\server.js:322:23)
[11ty]     at EleventyDevServer.eleventyDevServerMiddleware (L:\DMT\smart-wc-library\node_modules\@11ty\eleventy\node_modules\@11ty\eleventy-dev-server\server.js:426:29)
[11ty]     at EleventyDevServer.onRequestHandler (L:\DMT\smart-wc-library\node_modules\@11ty\eleventy\node_modules\@11ty\eleventy-dev-server\server.js:548:11)
[11ty]     at Server.emit (node:events:518:28)
[11ty]     at parserOnIncoming (node:_http_server:1143:12)
[11ty]     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
```

### Root Cause Details:

The [`EleventyDevServer._getFileContents`](https://github.com/11ty/eleventy-dev-server/blob/2e41ce7ab571192061c447d3f9e6a1c1590c3c94/server.js#L318) method tries to read the file content of the `morphdom` module ([ref](https://github.com/11ty/eleventy-dev-server/blob/2e41ce7ab571192061c447d3f9e6a1c1590c3c94/server.js#L488)), but it cannot resolve the path to the file.
It uses the following path as a base `./node_modules/morphdom/dist/morphdom-esm.js` to create the following `searchLocations`:

```javascript
[
  'root/11ty-package/node_modules/morphdom/dist/morphdom-esm.js',
  'root/node_modules/@11ty/eleventy/node_modules/@11ty/eleventy-dev-server/node_modules/morphdom/dist/morphdom-esm.js',
  'root/node_modules/@11ty/eleventy/node_modules/morphdom/dist/morphdom-esm.js'
]
```
None of them contain `morphdom`, which is under `root/node_modules/morphdom/**` in the current state of things.

**Comment by zachleat** [comment]
Marginally related to https://github.com/11ty/eleventy/issues/3178

**Comment by ala-n** [comment]
Sure, 

The actual command in `root/11ty-package/pacage.json` (runs in the context of `root/11ty-package`) is:
```bash
 eleventy --serve --incremental -- --env=development
```
The `-- --env=development` part is not directly related to the 11ty server (included just in case it indirectly affects something) 

Running through workspaces root (e.g., `npm run serve -w 11ty-package`) does not affect path resolution.

**Comment by vrugtehagel** [comment]
I just ran into this issue with Deno. Deno doesn't usually create a `node_modules`, so this `_getFileContents` on the `morphdom` package fails. While the serving itself remains functional, I can no longer exit with ctrl+C, but instead I have to manually kill the process or close the terminal window (effectively doing the same thing).

For those looking for a quick fix, you can turn off DOM diffing through

```js
eleventConfig.setServerOptions({ domDiff: false })
```

<details><summary>Reproduction steps</summary>

First, set up a simple project and run the server using Deno:

```bash
mkdir test
cd test
echo "Hello world" > index.md
deno run -A npm:@11ty/eleventy@3.0.0 --serve --loader=esm
```

Then open your browser and navigate to [localhost:8080](http://localhost:8080/) (this is important! If it is already open, you may need to manually reload it first). Next, in a different terminal tab, run

```bash
echo "Goodbye, world…" > index.md
```

And the following error appears in the terminal window that is serving:


```
[11ty] Unhandled rejection in promise:
[11ty] EISDIR: illegal operation on a directory, open
[11ty] 
[11ty] Original error stack trace: Error: EISDIR: illegal operation on a directory, open
[11ty]     at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
[11ty]     at __node_internal_uvException (ext:deno_node/internal/errors.ts:186:10)
[11ty]     at denoErrorToNodeError (ext:deno_node/internal/errors.ts:1898:14)
[11ty]     at Object.readFileSync (ext:deno_node/_fs/_fs_readFile.ts:67:13)
[11ty]     at EleventyDevServer._getFileContents (file:///Users/koen/Library/Caches/deno/npm/registry.npmjs.org/@11ty/eleventy-dev-server/2.0.6/server.js:353:23)
[11ty]     at EleventyDevServer.eleventyDevServerMiddleware (file:///Users/koen/Library/Caches/deno/npm/registry.npmjs.org/@11ty/eleventy-dev-server/2.0.6/server.js:506:29)
[11ty]     at EleventyDevServer.onRequestHandler (file:///Users/koen/Library/Caches/deno/npm/registry.npmjs.org/@11ty/eleventy-dev-server/2.0.6/server.js:633:11)
[11ty]     at ServerImpl.emit (ext:deno_node/_events.mjs:393:28)
[11ty]     at node:http:1450:18
[11ty]     at new Promise (<anonymous>)
```

</details>

Given the cryptic nature of the error, I initially mistakenly thought this was a deeper filesystem-related issue, but it turns out it's because we're just passing `undefined` to `fs.readFileSync()` while trying to do DOM diffing.

My suggestion: when the file path to `morphdom` wasn't found, we should either

- when the file path to `morphdom` wasn't found, throw a readable error that suggests turning DOM diffing off
- when the file path to `morphdom` wasn't found, log a warning saying DOM diffing failed, but continue without DOM diffing.
- bundle a version of `morphdom` into the dev server. This is not a pretty idea, but `morphdom` doesn't have dependencies and a quick bundle with `esbuild` shows a ~5kB footprint.

There are arguments to be made for either of the first two options, and the latter is really just fixing the underlying error rather than making the error more palatable for the user.

@zachleat what do you reckon is best here? Happy to open a PR for whatever we choose to do.

**Comment by zachleat** [comment]
Swapped to use `require.resolve` to locate the module (as it should have used before), which I verified to work in Deno!

This will ship with Dev Server v2.0.7
