### ISSUE TITLE
404 missing file error on range requests (video) throws error

### ISSUE THREAD

**Issue by zachleat** [11ty/eleventy-dev-server#98]
```
[11ty] Original error stack trace: TypeError: Cannot read properties of undefined (reading 'length')
[11ty]     at SendStream.hasTrailingSlash (/Users/zachleat/Code/eleventy-base-blog/node_modules/send/index.js:302:30)
[11ty]     at SendStream.pipe (/Users/zachleat/Code/eleventy-base-blog/node_modules/send/index.js:585:34)
[11ty]     at EleventyDevServer.eleventyProjectMiddleware (/Users/zachleat/Code/eleventy-base-blog/node_modules/@11ty/eleventy-dev-server/server.js:544:44)
[11ty]     at EleventyDevServer.eleventyDevServerMiddleware (/Users/zachleat/Code/eleventy-base-blog/node_modules/@11ty/eleventy-dev-server/server.js:510:5)
[11ty]     at EleventyDevServer.onRequestHandler (/Users/zachleat/Code/eleventy-base-blog/node_modules/@11ty/eleventy-dev-server/server.js:634:11)
[11ty]     at Server.emit (node:events:518:28)
[11ty]     at parserOnIncoming (node:_http_server:1150:12)
[11ty]     at HTTPParser.parserOnHeadersComplete (node:_http_common:117:17)
```

https://github.com/11ty/eleventy-dev-server/blob/f0bfd27771e706606cb4b37b03d8759af55f8cf5/server.js#L543 where `match` contains `{ statusCode: 404 }`

**Comment by zachleat** [comment]
Shipping with Dev Server v2.0.5 and Core v3.0.1 (v3.0.1-alpha.4)
